apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked,A unique name
  name: Mall
spec:
  enabled: true
  # 'version' is a valid semantic version string (see semver.org).
  version: 1.0.0-SNAPSHOT
  requires: "*"
  author:
    name: pannanxu
    website: https://github.com/pannanxu
  logo: https://mvvm.io/logo
  settingName: mall-settings
  configMapName: mall-settings
  # 'homepage' usually links to the GitHub repository of the plugin
  homepage: https://github.com/pannanxu/halo-plugin-mall
  # 'displayName' explains what the plugin does in only a few words
  displayName: "Halo Mall"
  description: "Halo 商城插件"
  license:
    - name: "MIT"
